######################################################################
# Automatically generated by qmake (3.0) Mon Nov 7 17:51:00 2016
######################################################################

TEMPLATE = app
TARGET = a3
INCLUDEPATH += .
CONFIG += c++11

# Input
SOURCES += main.cpp
